### PR TITLE
Make IndexEntry take a base_dir so prefixes and tags can be correct

### LINKED ISSUE #39: Incorrect `prefixes` when indexing checkpoints that have no tags
If I save a checkpoint called "Forecasters.predicted" in `example/path` without tags, the filepath is `example/path/Forecasters/predicted.jlso`.

This [`IndexEntry` constructor](https://github.com/invenia/Checkpoints.jl/blob/f380d77731a3706286806c06c21633aec1d76fa1/src/indexing.jl#L21-L34) assumes that prefixes are those paths segments which do not contain "=", i.e. are not tags. However, when there are no tags in the first place, all path segments will be included in this operation, because `first_tag_ind` defaults to 1: https://github.com/invenia/Checkpoints.jl/blob/f380d77731a3706286806c06c21633aec1d76fa1/src/indexing.jl#L24-L27

MWE:

```julia
julia> Checkpoints.register("Forecasters", ["predicted"])

julia> Checkpoints.config("Forecasters.predicted", "example/path")

julia> checkpoint("Forecasters.predicted", [1])
13361

julia> IndexEntry("example/path/Forecasters/predicted.jlso").prefixes
("example", "path", "Forecasters")
```

### PR DESCRIPTION
**Pull request by oxinabox**
closes #39 

Right now the `base_dir` directory is required.
I kinda think it is fine because noone should be constructing `IndexEntry`'s directly anyway

### CODE REVIEW

File: test/indexing.jl [hunk 1]
```diff
@@ -20,6 +20,23 @@
         end
     end
 
+    @testset "Searching within a nontrivial directory" begin
+        # https://github.com/invenia/Checkpoints.jl/issues/39
+        mktempdir() do outer_path
+            # This path is tricky, it is more than 1 folder deep
+            # and it has `=` in bits that are not tags
+            path = mkdir(joinpath(mktempdir(Path),"a","b=1","c"); recursive=true)
```
Comment (bencottier) [inline test/indexing.jl:28]: `outer_path` was unused, did you mean

```suggestion
        mktempdir() do outer_path
            # This path is tricky, it is more than 1 folder deep
            # and it has `=` in bits that are not tags
            path = mkdir(joinpath(outer_path,"a","b=1","c"); recursive=true)
```

Note I didn't find a `mktempdir(Path)` method that allows `do` block so just using String.

File: src/indexing.jl [hunk 2]
```diff
@@ -17,12 +24,9 @@ struct IndexEntry
     tags::NTuple{<:Any, Pair{Symbol, <:AbstractString}}
 end
 
-IndexEntry(file) = IndexEntry(Path(file))
-function IndexEntry(filepath::AbstractPath)
-    # skip any non-tag directories at the start. Note this will be tricked if those have "="
-    # in them but probably not worth handling, unless an issue comes up
-    first_tag_ind = something(findfirst(contains("="), filepath.segments), 1)
-    segments = filepath.segments[first_tag_ind:end-1]
+IndexEntry(file, base_dir) = IndexEntry(Path(file), Path(base_dir))
```
Comment (bencottier) [inline src/indexing.jl:27]: This is not tested but I notice that in general we aren't testing `IndexEntry` directly.

Might be orthogonal to changes, but why do we have this anyway? It looks like `index_checkpoint_files` will always pass in `AbstractPath`.

**Comment by bencottier** [comment]
For the `index_checkpoint_files` docstring I would add a line like:

```
To determine checkpoint prefixes, this assumes that any subfolder which is not a tag is a prefix.
```

**Review by bencottier — APPROVED** [review]
Looks good, I have some comments to address.

File: src/indexing.jl (hunk 2 above)
Comment (oxinabox) [reply src/indexing.jl:27]: correct.
Lets delete it

```suggestion
```

File: test/indexing.jl [hunk 3]
```diff
@@ -20,6 +20,23 @@
         end
     end
 
+    @testset "Searching within a nontrivial directory" begin
+        # https://github.com/invenia/Checkpoints.jl/issues/39
+        mktempdir() do outer_path
+            # This path is tricky, it is more than 1 folder deep
+            # and it has `=` in bits that are not tags
+            path = mkdir(joinpath(outer_path,"a","b=1","c"); recursive=true)
```
Comment (oxinabox) [inline test/indexing.jl:28]:
```suggestion
            path = mkdir(joinpath(Path(outer_path),"a","b=1","c"); recursive=true)
```
